<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace app\assets;

use yii\web\AssetBundle;

/**
 * Main application asset bundle.
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class MAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';

    public function registerAssetFiles($view)
    {
        //版本号是一个常量，加载js或者css是有业务逻辑的
        $version = defined('VERSION')?VERSION:time();

        $this->css = [
        ];

        $this->js = [
            'plugins/jquery-2.1.1.js',
            'js/m/TouchSlide.1.1.js',
            'js/m/common.js?ver='.$version
        ];
        parent::registerAssetFiles($view); // TODO: Change the autogenerated stub
    }
}
